/*
* generated by Xtext
*/
package com.github.jmodel.mapper.plugin.ui.outline

//import com.github.jmodel.mapper.plugin.lang.MappingBlock

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class MappingLanguageOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
//	def _isLeaf(MappingBlock a) { true }
}
