/*
 * generated by Xtext
 */
package com.github.jmodel.mapper.plugin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MappingLanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.github.jmodel.mapper.plugin.ui.internal.MappingLanguageActivator.getInstance().getInjector("com.github.jmodel.mapper.plugin.MappingLanguage");
	}
	
}
